import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Theme } from '@radix-ui/themes';
import Header from '@/components/shared/Header/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme appearance="dark">
          <Header />
          <div id="main">{children}</div>
        </Theme>
      </body>
    </html>
  );
}
